CC = mpicc
CFLAGS = -Wall --std=c11

hello_world:
	$(CC) $(CFLAGS) 4_6_hello_world.c -o $@

reduction_sum:
	$(CC) $(CFLAGS) 4_7_reduction_sum.c -o $@

est:
	$(CC) $(CFLAGS) 6_8_est.c -o $@

clean:
	rm hello_world reduction_sum est